#include "cpcrslib.h"
#include "cpcwyzlib.h"	//Music & Sound library

extern unsigned char SONG_TABLE[];
extern unsigned char EFFECT_TABLE[];
extern unsigned char RULE_TABLE[];
extern unsigned char SOUND_TABLE[];


main(){
	
	
	cpc_ClrScr();
	
	// Text writting using firmware:
	cpc_PrintStr();
	cpc_PrintStr("SFX & MUSIC DEMO. CPCRSLIB 2010");
	cpc_PrintStr("PSG PROPLAYER BY WYZ 2010");	
	cpc_PrintStr("Press keys 1 to 4 to play SFX");
	cpc_PrintStr("ESC to Quit");
	
	cpc_DisableFirmware();	
	// Assign keys to key number (not numberpad keys)
	cpc_AssignKey(0,0x4801);		// key "1" assigned to 0
	cpc_AssignKey(1,0x4802);		// key "2"
	cpc_AssignKey(2,0x4702);		// key "3"
	cpc_AssignKey(3,0x4701);		// key "4"
	
	cpc_AssignKey(4,0x4804);		// key "ESC"
	
	

	cpc_WyzInitPlayer(SOUND_TABLE, RULE_TABLE, EFFECT_TABLE, SONG_TABLE);		//initialize data
	cpc_WyzLoadSong(0);	//Select song to play (uncompress it and the start to play)


	cpc_WyzSetPlayerOn();		//start music and sound effects (SFX)

	cpc_ScanKeyboard();			//Reads whole keyboard. It's requiered in order to use cpc_TestKeyF
	while (!cpc_TestKeyF(4)) {	//cpc_TestKeyF is faster when more than 3 keys gonna be tested
		cpc_ScanKeyboard();
		if ((cpc_WyzTestPlayer()&8)==0) {	//test if bit 3 is 0 in order to allow another effect.
			// When a  1-4 key is pressed, a SFX is played
			if (cpc_TestKeyF(0)==1) 	cpc_WyzStartEffect(0,0);	//(Channel, SFX #)
			if (cpc_TestKeyF(1)==1) 	cpc_WyzStartEffect(1,1);
			if (cpc_TestKeyF(2)==1) 	cpc_WyzStartEffect(2,2);
			if (cpc_TestKeyF(3)==1) 	cpc_WyzStartEffect(1,3); 
		} 
	}
	cpc_WyzSetPlayerOff();	//stop music and SFX
	cpc_EnableFirmware();
	return 0;
		
}




// Music Player requiered data
#asm		

._SONG_TABLE 
	DEFW _SONG_0
	
._SONG_0 BINARY "Wyazow.mus"			//Song file to be included


._RULE_TABLE
defw _PAUTA_1,_PAUTA_2,_PAUTA_3,_PAUTA_4,_PAUTA_5,_PAUTA_6,_PAUTA_7

// from *.mus.asm file generated by WYZTracker:

._PAUTA_1	DEFB	46,0,13,0,12,0,11,0,10,0,9,0,128+1
._PAUTA_2	DEFB	8,0,74,0,11,0,43,0,10,0,9,0,8,0,7,0,$40+6,0,6,0,$20+6,0,6,0,132
._PAUTA_3	DEFB	6,0,71,0,8,0,40,0,8,0,71,0,$40+4,0,4,0,$20+4,0,4,0,132
._PAUTA_4	DEFB	77,0,12,0,12,0,11,0,11,0,11,0,10,0,9,0,8,-1,8,0,8,0,8,1,8,1,8,0,8,0,8,-1,128+8
._PAUTA_5	DEFB	75,0,10,0,9,0,9,0,8,0,8,-1,8,0,8,0,8,1,8,1,8,0,8,0,8,-1,128+8
._PAUTA_6	DEFB	5,0,70,0,7,0,38,0,5,0,3,0,129
._PAUTA_7	DEFB	71,0,6,0,5,0,5,0,5,0,4,0,129




._SOUND_TABLE
		defw _SONIDO1
		defw _SONIDO2
		defw _SONIDO3
		defw _SONIDO4
		defw _SONIDO5


// from *.mus.asm file generated by WYZTracker:

._SONIDO1	DEFB	209,63,0,69,173,0,255
._SONIDO2	DEFB	93,47,0,209,14,11,255
._SONIDO3	DEFB	0,11,1,255
._SONIDO4	DEFB	186,57,0,0,102,0,162,131,0,255
._SONIDO5	DEFB	0,12,14,255





//SFX
/*
SFX format is quite simple:

defb byte1,byte2
defb byte1,byte2
...
defb &ff

Where byte 1 and bits 7, 6, 5 & 4 from byte2 are the sound frequency and bits 3, 2, 1 & 0 of byte2 is the amplitude. 
Effect finishes when &ff is found.
*/

._EFFECT_TABLE
		defw _EFECTO0
		defw _EFECTO1
		defw _EFECTO2
		defw _EFECTO3


._EFECTO0                

defb $58,$0D
defb $50,$0B
defb $47,$0A
defb $3E,$06
defb $35,$03
defb $50,$09
defb $47,$0A
defb $3E,$07
defb $FF

._EFECTO1                

defb $58,$0C
defb $5D,$0D
defb $61,$0E
defb $66,$0F
defb $6A,$0E
defb $6F,$0D
defb $7A,$0C
defb $78,$0B
defb $7C,$0A
defb $85,$09
defb $8E,$08
defb $97,$07
defb $A0,$06
defb $A9,$05
defb $FF


._EFECTO2               

defb $1F,$0B
defb $1A,$0C
defb $1F,$0D
defb $16,$0E
defb $1F,$0E
defb $0D,$0D
defb $1F,$0C
defb $0D,$0B
defb $00,$00
defb $00,$00
defb $1F,$08
defb $1A,$09
defb $1F,$0A
defb $16,$0B
defb $1F,$0B
defb $0D,$0A
defb $1F,$09
defb $0D,$07
defb $00,$00
defb $00,$00
defb $1F,$06
defb $1A,$07
defb $1F,$08
defb $16,$08
defb $1F,$07
defb $0D,$06
defb $1F,$05
defb $FF

._EFECTO3                

defb $1A,$0E
defb $1A,$0E
defb $00,$00
defb $1A,$0A
defb $1A,$0A
defb $00,$00
defb $1A,$0C
defb $1A,$0C
defb $00,$00
defb $1A,$08
defb $1A,$08
defb $FF




#endasm



